name: ionhive
description: "Ion Hive - Your ultimate companion for finding, charging, and managing EV stations effortlessly."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.2
  pinput: ^5.0.0
  flutter_spinkit: ^5.1.0
  package_info_plus: ^8.1.2
  flutter_native_splash: ^2.2.20
  shared_preferences: ^2.3.4
  connectivity_plus: ^6.1.1
  permission_handler: ^11.3.1
  webview_flutter: ^4.10.0
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4
  flutter_blue_classic: ^0.0.3 #TODO - For bluetooth devices connection
  webview_flutter_wkwebview: ^3.17.0
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ionHive_logo's/ionHive.png

flutter_native_splash:
  color: "#000000" 
  image: assets/ionHive_logo's/ionHive.png 
  android: true
  ios: true
  web: true
  fullscreen: true
